pcs resource delete postgresql
pcs resource delete content
pcs resource delete heartbeat
pcs resource delete hermes
pcs resource delete mastercontrol
pcs resource delete motion
pcs resource delete rabbitmq
pcs resource delete ui
pcs resource delete websocket
#pcs resource delete p_awsvip
#pcs resource delete sql
pcs resource delete keycloak
pcs resource delete ingest
pcs resource delete httpbridge
pcs resource delete integration
pcs resource delete vip
