version: "3.6"

services:
  rabbitmq:
      image: rabbitmq:3.8.14-management
      hostname: "r-{{.Node.Hostname}}"
      ports:
        - 15672:15672
        - target: 5672
          published: 5672
          protocol: tcp
          mode: host
        - target: 15692
          published: 15692
          protocol: tcp
          mode: host
      networks:
        - imagine_poc
      environment:
        - RABBITMQ_DEFAULT_USER=admin
        - RABBITMQ_DEFAULT_PASS=ImagineDB1
        - RABBITMQ_ERLANG_COOKIE="PLMMC-RABBITMQ"
      volumes:
        - rmqdata:/var/lib/rabbitmq
        - /etc/imagine/config/rabbitmq:/etc/rabbitmq:rw
      deploy:
#        endpoint_mode: dnsrr
        mode: global
      logging:
        driver: syslog
        options:
          syslog-address: udp://10.119.106.106:514
          tag: Rabbit

networks:
  imagine_poc:
    external: true

volumes:
  rmqdata:
