version: "3.6"
services:
  playlist:
    image: deploy.imaginecommunications.com:443/versio-docker-rel/vauto-web-ui:4.6.1.41-linux
    ports:
      - target: 80
        published: 10443
        protocol: tcp
        mode: host
    environment:
      - IDENTITY_SERVER=10.121.107.172
      - IDENTITY_SERVER_PORT=8081
      - HERMES_HOST=10.121.214.100
      - HERMES_PORT=9872
      - KEYCLOAK_REALM=Versio
      - ENABLE_AUTH=true
      - WEBSOCKET_HOST=10.121.214.100
      - CONTENT_HOST=10.121.214.100
    networks:
      - webui
    deploy:
      mode: global
      placement:
        constraints:
          - node.labels.vip == op2
 
  redundancy:
    image: deploy.imaginecommunications.com:443/versio-docker-rel/vauto-redundancy-web-ui:4.6.0.172-linux
    ports:
      - target: 80
        published: 10444
        protocol: tcp
        mode: host
    environment:
      - HERMES_HOST=10.121.214.100
      - HERMES_PORT=9872
      - WEBSOCKET_HOST=10.121.214.100
    networks:
      - webui
    deploy:
      mode: global
      placement:
        constraints:
          - node.labels.vip == op2
      # endpoint_mode: dnsrr

  mcp:
    image: deploy.imaginecommunications.com:443/versio-docker-rel/master-control-ui:0.0.3.8-linux
    ports:
      - target: 80
        published: 10445
        protocol: tcp
        mode: host
    environment:
      - HERMES_HOST=10.121.214.100
      - MCS_HOST=10.121.214.100
      - CONTENT_HOST=10.121.214.100
      - WEBSOCKET_HOST=10.121.214.100
      - IDENTITY_SERVER=10.121.107.172
      - IDENTITY_SERVER_PORT=8081
      - HOT_SWIZZLE=true
    networks:
      - webui
    deploy:
      mode: global
      placement:
        constraints:
          - node.labels.vip == op2
      # endpoint_mode: dnsrr

  contentportal:
    image: deploy.imaginecommunications.com:443/versio-docker-rel/contentportal-webui:4.6.0.72-linux
    ports:
      - target: 80
        published: 10446
        protocol: tcp
        mode: host
    environment:
      - IDENTITY_SERVER=10.121.107.172
      - IDENTITY_SERVER_PORT=8081
      - HERMES_HOST=10.121.214.100
      - HERMES_PORT=9872
      - KEYCLOAK_REALM=Versio
      - ENABLE_AUTH=true
    networks:
      - webui
    deploy:
      mode: global
      placement:
        constraints:
          - node.labels.vip == op2
      # endpoint_mode: dnsrr
     
  settingsui:
    image: deploy.imaginecommunications.com:443/versio-docker-rel/vauto-settings-ui:4.6.0.172
    networks:
      - webui
    ports:
      - target: 80
        published: 10450
        protocol: tcp
        mode: host
    environment:
      - IDENTITY_SERVER=10.121.107.172
      - IDENTITY_SERVER_PORT=8081
      - HERMES_HOST=10.121.214.100
      - HERMES_PORT=9872
      - KEYCLOAK_REALM=Versio
      - ENABLE_AUTH=true
      - SPINUP_SERVICE_HOST=1.1.1.1
      - SPINUP_SERVICE_PORT=30001
      - WEBSOCKET_HOST=10.121.214.100
    deploy:
      mode: global
      placement:
        constraints:
          - node.labels.vip == op2

 
  # ingestui:
  #   image: deploy.imaginecommunications.com:443/versio-docker-rel/versio-ingest-webui:0.0.1.1-linux
  #   ports:
  #     - target: 80
  #       published: 10449
  #       protocol: tcp
  #       mode: host
  #   networks:
  #     - webui
  #   environment:
  #     - IDENTITY_SERVER=$ALB_HOSTNAME
  #     - IDENTITY_SERVER_PORT=8081
  #     - HERMES_HOST=198.19.1.10
  #     - HERMES_PORT=9872
  #     - KEYCLOAK_REALM=Versio
  #     - ENABLE_AUTH=true
  #   deploy:
  #     mode: global


#  settings-ui:
#    image: deploy.imaginecommunications.com:443/versio-docker-rel/vauto-settings-ui:0.4.0
#    volumes:
#      - type: bind
#        source: /etc/imagine/config/settingsuiconfig/config
#        target: /etc/nginx/templates
#      - type: bind
#        source: /etc/imagine/config/global/identityserver.auth.config.json
#        target: /usr/share/nginx/html/AuthService/config/identityserver.auth.config.json
#    networks:
#      - webui
#    ports:
#      - "10000:80"
#    environment:
#      #envsubst will remove ".template" extension after substituting env vars.
#      - NGINX_ENVSUBST_TEMPLATE_DIR=/etc/nginx/templates
#      - NGINX_ENVSUBST_TEMPLATE_SUFFIX=.template
#      - NGINX_ENVSUBST_OUTPUT_DIR=/usr/share/nginx/html/config # Where UI will look for configs
#      - SPINUP_SERVICE_HOSTNAME=198.19.1.10
#      - SPINUP_SERVICE_PORT=30000
#      - IDENTITY_SERVER=198.19.1.10
#      - HERMES_HOSTNAME=198.19.1.10
#      - WEBSOCKET_HOSTNAME=198.19.1.10
#    deploy:
#      mode: global
      # endpoint_mode: dnsrr

  # proxy:
  #   image: haproxy:2.1.7-alpine
  #   ports:
  #     - 10442:10442
  #     - 8404:8404
  #   networks:
  #     - webui
  #   volumes:
  #     - type: bind
  #       source: /etc/imagine/config/vauto-webui/haproxy
  #       target: /usr/local/etc/haproxy
  #   deploy:
  #     replicas: 1
  #     placement:
  #       constraints:
  #         - node.role == manager

networks:
  webui:
    external: true
