version: "3.6"
services:
  auth-config:
    image: deploy.imaginecommunications.com:443/versio-docker-rel/versio-auth-config:2.0.0.18-alpine
    environment:
      - VERSIOAUTHCONFIG_OVERWRITEJSON=true
      - VERSIOAUTHCONFIG_IDENTITYSERVERURL=http://10.121.107.172:8081/auth/realms/Versio
      - VERSIOAUTHCONFIG_KEYCLOAKADMINUSER=admin
      - VERSIOAUTHCONFIG_KEYCLOAKADMINPASSWORD=Pa55w0rd
      - VERSIOAUTHCONFIG_HERMESHOST=10.121.204.100
      - VERSIOAUTHCONFIG_MAX_RETRIES=50
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
