
version: "3.6"

services:

    aux-service-deploy:
        image: deploy.imaginecommunications.com:443/versio-docker-rel/vauto-aux-services-db:4.6.0.172-alpine
        environment:
            - PG_HOST=10.121.204.100
            - PG_USER=postgres
            - PG_PASSFILE=/run/secrets/db_pass
        secrets:
            - db_pass
        deploy:
            replicas: 1
            placement:
                constraints:
                - node.role == manager

secrets:
    db_pass:
        file: /etc/imagine/config/content/db_pass.txt
