version: "3.6"

services:
  keycloak:
    image: deploy.imaginecommunications.com:443/versio-docker-rel/versio-keycloak:11.0.3-1.0.1
    ports:
      - target: 8443
        published: 8443
        protocol: tcp
        mode: host
      - target: 8080
        published: 8081
        protocol: tcp
        mode: host
    networks:
      - imagine_poc
    environment:
      DB_VENDOR: postgres
      DB_ADDR: 10.121.204.100
      DB_PORT: 5432
      DB_DATABASE: keycloak
      DB_USER: postgres
      DB_PASSWORD: ImagineDB1
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: Pa55w0rd
      KEYCLOAK_FRONTEND_URL: http://10.121.107.172:8081/auth
      PROXY_ADDRESS_FORWARDING: "true"
    deploy:
      # mode: global
      replicas: 1
      placement:
        constraints:
          - node.labels.vip == op1

networks:
  imagine_poc:
    external: true
