global:
  resolve_timeout: 5m
  #slack_api_url: 'https://hooks.slack.com/services/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'


route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
#  receiver: 'slack-notifications'
#receivers:
#- name: 'slack-notifications'
#  slack_configs:
#  - channel: '#plmsysalerts'
#    send_resolved: true

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']

